# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_action_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    joints:
      - Revolute_2
      - Revolute_4
      - Revolute_8
      - Revolute_11
      - Revolute_13
      - Revolute_16
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_integration_in_goal_trajectories: true
    allow_nonzero_velocity_at_trajectory_end: false
    allow_partial_joints_goal: true

gripper_action_controller:
  ros__parameters:
    joints:
      - Revolute_18
    command_interfaces:
      - position
    state_interfaces:
      - position
    open_loop_control: true
    allow_integration_in_goal_trajectories: true

